services:
  web-interface:
    image: stayking-house/web-interface
    container_name: "stayking-web-interface"
    profiles:
      - local
      - dev
      - prod
    build:
      context: ../submodules/web-interface
      dockerfile: Dockerfile.local
    volumes:
      - ../submodules/web-interface:/app
      - /app/.next
    environment:
      NEXT_PUBLIC_APP_ENV: ${APP_ENV}
      NEXT_PUBLIC_WEB_CLIENT_PORT: ${WEB_CLIENT_PORT}
      NEXT_PUBLIC_API_SERVER_URL: ${API_SERVER_URL}
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    stdin_open: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
